use_frameworks!

platform :ios, '8.0'

target 'YYTestWorking_Example' do
  pod 'YYTestWorking', :path => '../'

  target 'YYTestWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
